#This yml file configures a eureka discovery server
eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself (unless running
           # multiple discovery servers for redundancy)
    registerWithEureka: false
    fetchRegistry: false

#server:
  #port: 2222  use default port for server instead of a new HTTP port on tomcat 