# Spring properties
spring:
  application:
     name: crimedata-service  # Register service as this


# HTTP Server
server:
  port: 8080   # HTTP (Tomcat) port 
 
eureka:
  client:
    serviceUrl: #use eureka default port
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10   # DO NOT DO THIS IN PRODUCTION

#  3. If using the Angel release-train ONLY, give the process a unique instance id 
#     so that multiple instances can register when running on SAME host.  This is
#     not needed since release-train Brixton.
#     NOTE-1: spring.application.instance_id is only set when run on Cloud Foundry,
#             so we fallback on the server-port when it is not defined
#     NOTE-2: Syntax ${x:${y}} = use $x if set, otherwise use $y
#   metadataMap:
#     instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}


# Enable actuator access without security checks - DEVELOPMENT ONLY
# Spring Boot 1.5
# management.security.enabled: false
# Spring Boot 2.x
management.endpoints.web.exposure.include: '*'


